{{- if .Values.configMap.enabled }}


apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-test.fullname" . }}
  namespace: {{ .Values.namespace }}

{{- with .Values.configMap.configMapDataValue }}
  {{- toYaml .  | nindent 0 }}
{{- end }} 

{{- end }}    