
{{- if .Values.externalSecret.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "my-test.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:  
{{- with .Values.externalSecret.exSecretDataValue }}
  {{- toYaml .  | nindent 0 }}
{{- end }} 

{{- end }}    