{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "my-test.fullname" . }}
  labels:
    {{- include "my-test.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}    
spec:
  scaleTargetRef:
    {{- if .Values.enable_Rollout_deploy }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{- else }}
    apiVersion: apps/v1
    kind: Deployment
    {{- end }}
    name: {{ include "my-test.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  
  metrics:
    {{- if .Values.autoscaling.memory_type.enable }}  
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.memory_type.averageUtilization }}
    {{- end }}        
    {{- if .Values.autoscaling.cpu_type.enable }}  
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.cpu_type.averageUtilization }}
    {{- end }}  
  
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleDown.stabilizationWindowSeconds }}
      policies:
      - type: Pods
        value: {{ .Values.autoscaling.scaleDown.policies_pod_value }}
        periodSeconds: {{ .Values.autoscaling.scaleDown.periodSeconds }}
      - type: Percent
        value: {{ .Values.autoscaling.scaleDown.policies_percent_value }}
        periodSeconds: {{ .Values.autoscaling.scaleDown.periodSeconds }}
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleUp.stabilizationWindowSeconds }}
      policies:
      - type: Pods
        value: {{ .Values.autoscaling.scaleUp.policies_pod_value }}
        periodSeconds: {{ .Values.autoscaling.scaleUp.periodSeconds }}
      - type: Percent
        value: {{ .Values.autoscaling.scaleUp.periodSeconds }}
        periodSeconds: {{ .Values.autoscaling.scaleUp.policies_percent_value }}
      selectPolicy: Max    
{{- end }}      
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: lms-learning-deployment
#   namespace: stg-lms
# spec:
#   maxReplicas: 4
#   minReplicas: 1
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: lms-learning-deployment
#   targetCPUUtilizationPercentage: 80
