{{- if .Values.ebs_pvc.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-test.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ebs_pvc.storageSize }}

{{- end }}    


{{- if .Values.efs_pvc.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-test.fullname" . }}-efs
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: efs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.efs_pvc.storageSize }}



{{- end }}    

