
{{- if .Values.secret.enabled }}


apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-test.fullname" . }}
  namespace: {{ .Values.namespace }}

{{- with .Values.secret.secretDataValue }}
  {{- toYaml .  | nindent 0 }}
{{- end }} 

{{- end }}    

