apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-test.fullname" . }}
  labels:
    {{- include "my-test.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "my-test.selectorLabels" . | nindent 4 }}
---
{{- if .Values.enable_Rollout_deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-test.fullname" . }}-preview
  labels:
    {{- include "my-test.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}        
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "my-test.selectorLabels" . | nindent 4 }}
{{- end }}    