
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an AWS EKS cluster

Parameters:
  ClusterName:
    Type: String
    Description: Name of the EKS cluster
  KubernetesVersion:  
    Type: String
    Description: >-
      (Optional) Kubernetes control plane version. If ConfigSetName is set,
      this value will be ignored and the Kubernetes version specified in the
      advanced configuration template (including the default) will be used.
    AllowedValues: [1.28,1.27, 1.26, 1.25, 1.24, 1.23]
    Default: 1.27
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID of the Amazon VPC for the cluster
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs in the VPC
  
Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ClusterSecurityGroup
        SubnetIds: !Ref SubnetIds
      Version: !Ref KubernetesVersion

  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ClusterName}-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  ClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the EKS cluster
      VpcId: !Ref VpcId

  
Outputs:
  ClusterNameOutput:
    Description: Name of the EKS cluster
    Value: !Ref ClusterName
  