version: 0.2
phases:
  install:
    commands:
      - echo install in to Amazon ECR...
      
      - AWS_ACCOUNT_ID2=557269744548
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID2.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      #- echo $(aws sts get-caller-identity)
  pre_build:
    commands:
      - echo pre_build ..
      - aws --version
      - REPOSITORY_URI=$AWS_ACCOUNT_ID2.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/virtlet-front
      - IMAGE_TAG=$(date "+%y%m%d-%H%M%S")-$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)            
  build:
    commands:              
      - docker build -t ${REPOSITORY_URI}:${IMAGE_TAG} .      
  post_build:
    commands:
      - echo " code build success "
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker tag ${REPOSITORY_URI}:${IMAGE_TAG} ${REPOSITORY_URI}:latest
      - docker push ${REPOSITORY_URI}:latest
      #- git 
      #- "printf '\ncommitref: %s\n' ${DOCKER_TAG} >> deployspec.yml" 
artifacts:
  files:
    #- deployspec.yml
    #- deploy/*
    - '**/*'
  discard-paths: no
  base-directory: .